[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minidocker"
version = "1.0.0"
dependencies = [
  "click",
]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["linux"]
package-dir = {"linux" = "."} 
